config/dev.exs
config/prod.exs
config/test.exs
lib/plugs/interval_plug.ex
lib/redis.ex
lib/redis/api.ex
lib/redis/interval_cache.ex
lib/redis/response_cache.ex
test/controllers/api/download_controller_test.exs
test/controllers/api/impression_controller_test.exs
test/plugs/interval_plug_test.exs
test/redis/conn_test.exs
test/redis/interval_cache_test.exs
test/redis/response_cache_test.exs
test/support/channel_case.ex
test/support/fake_redis.ex
web/controllers/api/download_controller.ex
web/controllers/api/episode_controller.ex
web/controllers/api/impression_controller.ex
web/controllers/api/podcast_controller.ex

See #4.  Define explicit contract/boundary for redis usage.
- 10 days at 15m
- 40 days at 1h
- 2.7 years at 1d
Considering doing the same thing for bigquery tests.  But for now, using `Mock` in the controllers is working fine.

Boundary-ize redis

---

.gitignore
README.md
config/dev.exs
config/prod.exs
config/test.exs
lib/castle.ex
lib/redis.ex
lib/redis/api.ex
lib/redis/conn.ex
lib/redis/partition_cache.ex
lib/rollup.ex
lib/rollup/data/totals_data.ex
lib/rollup/jobs/totals_job.ex
lib/rollup/task.ex
lib/rollup/worker.ex
mix.exs
mix.lock
test/controllers/api/episode_controller_test.exs
test/controllers/api/podcast_controller_test.exs
test/redis/partition_cache_test.exs
test/rollup/data/totals_data_test.exs
test/rollup/jobs/totals_job_test.exs
test/support/fake_redis.ex
test/views/api/episode_view_test.exs
test/views/api/podcast_view_test.exs
web/controllers/api/episode_controller.ex
web/controllers/api/podcast_controller.ex
web/views/api/episode_view.ex
web/views/api/podcast_view.ex

See #24.
The `totals_job.ex` is probably just the beginning for things we want to roll up from a background worker.  But will implement other dashboard-ish data from other PRs.

Async caching strategy

---

lib/big_query.ex
lib/big_query/base/timestamp.ex
lib/big_query/base/timestamp_group.ex
lib/plugs/group_plug.ex
test/big_query/base/timestamp_group_test.exs
test/plugs/group_plug_test.exs

See #23.
Refactor the `?group=` SQL to join the geonames/agentnames tables first, and then group.  Used to do it the other way around ... group by city_id/country_id/etc, and then join.  This seems to be nearly as quick, and consumes the same amount of query-MBs.
And added these `?group=` params: `metrocode` / `subdiv1` / `subdiv2` / `countryiso`.

More geo groupings

---

lib/plugs/interval/time_from.ex
lib/plugs/interval/time_to.ex
test/plugs/interval/time_from_test.exs
test/plugs/interval/time_to_test.exs

Was parsing datetimes in whatever timezone they came in as, then sending that to BigQuery.  And it turned out, BQ doesn't like certain timezone strings.  So just convert everything to UTC on the way in.

Parse to UTC datetimes

---

lib/big_query.ex
lib/big_query/base/timestamp.ex
lib/big_query/base/timestamp_group.ex
lib/big_query/downloads.ex
lib/big_query/impressions.ex
lib/redis.ex
lib/redis/api.ex
lib/redis/conn.ex
lib/redis/interval/getter.ex
lib/redis/interval/keys.ex
lib/redis/interval/setter.ex
lib/redis/interval_cache.ex
test/big_query/base/timestamp_test.exs
test/big_query/downloads_test.exs
test/big_query/impressions_test.exs
test/controllers/api/download_controller_test.exs
test/controllers/api/impression_controller_test.exs
test/redis/conn_test.exs
test/redis/interval_cache/getter_test.exs
test/redis/interval_cache/keys_test.exs
test/redis/interval_cache/setter_test.exs
test/redis/interval_cache_test.exs
test/support/big_query_case.ex
test/support/fake_redis.ex
test/support/time_helpers.ex
web/controllers/api/download_controller.ex
web/controllers/api/impression_controller.ex

🚧 WIP :crazy-idea:
This allows setting downloads/impressions cache keys in such a way that they:
1. Can always be fetched on-demand by Castle, in reasonable time, with the in-progress intervals expiring in 5 minutes
2. Can be INCR'd by an external lambda in a way to prevent Castle from recalculating them
3. Can be (eventually, not in this PR) recalculated by a Castle worker, at the top of every hour, to true-up the numbers
Previously, our cache keys looked something like:
```
downloads.podcast.70.HOUR.2017-10-19T08:00:00Z = 14841
downloads.podcast.70.HOUR.2017-10-19T09:00:00Z = 14832
downloads.episode.94b247a3-3d7c-4a07-97aa-95f87c539093.15MIN.2017-10-18T21:15:00 = 18505
```
Which for one, results in just a ton of cache keys.  Plus it makes it more difficult to redis-INCR them from an …

Better downloads/impressions cache logic

---

lib/big_query/base/http.ex
lib/big_query/base/query.ex
lib/big_query/base/query_result.ex
lib/big_query/base/timestamp.ex
test/big_query/base/query_result_test.exs
test/big_query/base/query_test.exs
test/big_query/base/timestamp_test.exs

Okay, so maybe this is more of a fix than a feat.
- The POST to [Jobs: query](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query) sometimes returns a `pageToken`
- Use this to GET the next page from [Jobs: getQueryResults](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/getQueryResults)
- Old results (flat):
```
2017-09-01T00:00:00Z, 123, 66
2017-09-01T00:00:00Z, 456, 77
2017-09-01T00:00:00Z, 789, 88
2017-09-01T01:00:00Z, 123, 99
```
- New results (array of structs of podcast-ids/counts):
```
2017-09-01T00:00:00Z, [{123, 66}, {456, 77}, {789, 88}]
2017-09-01T01:00:00Z, [{123, 99}]
```

Paging and optimize grouping

---

lib/big_query/base/timestamp.ex
lib/big_query/timestamp_rollup.ex
lib/big_query/timestamp_rollups/daily.ex
lib/big_query/timestamp_rollups/hourly.ex
lib/big_query/timestamp_rollups/monthly.ex
lib/big_query/timestamp_rollups/quarter_hourly.ex
lib/big_query/timestamp_rollups/weekly.ex
lib/plugs/interval_plug.ex
lib/redis/interval/getter.ex
lib/redis/interval_cache.ex
test/big_query/base/timestamp_test.exs
test/big_query/downloads_test.exs
test/big_query/impressions_test.exs
test/big_query/timestamp_rollups/daily_test.exs
test/big_query/timestamp_rollups/hourly_test.exs
test/big_query/timestamp_rollups/monthly_test.exs
test/big_query/timestamp_rollups/quarter_hourly_test.exs
test/big_query/timestamp_rollups/weekly_test.exs
test/plugs/interval_plug_test.exs
test/redis/interval_cache/getter_test.exs
test/redis/interval_cache_test.exs
test/support/big_query_case.ex

I was still doing interval ranges wrong.  Here's what it does now (easiest to explain by example):
```
-> returns 3 rows 
-> queries for timestamp >= 2017-07-15T00:00:00 AND timestamp < 2017-07-18T00:00:00
-> returns 3 rows
-> interval plug floor()s both dates ... so it ends up being the same as the first example
-> returns 4 rows 
-> queries for timestamp >= 2017-07-15T00:00:00 AND timestamp < 2017-07-19T00:00:00
```

Fix interval ranges

---

lib/castle_web/controllers/api/bucket_helper.ex
test/controllers/api/bucket_helper_test.exs

In the case where the first bucket of data is offset from the beginning-of-day/week/month ... return the offset timestamp for the first bucket.
For example, previously, asking for `?interval=1M&from=2017-10-09&to=2017-11-09` would have returned (with 1234 and 5678 being the "partial" downloads for those months):
```js
{
downloads: [
["2017-10-01T00:00:00Z", 1234],
["2017-11-01T00:00:00Z", 5678]
]
}
```
Now it will return:
```js
{
downloads: [
["2017-10-09T00:00:00Z", 1234],
["2017-11-01T00:00:00Z", 5678]
]
}
```

First bucket time offset

---

lib/big_query/base/query.ex
lib/plugs/interval/rollups.ex
mix.exs
mix.lock
test/plugs/interval/rollups_test.exs
test/plugs/interval_plug_test.exs

Hitting the memory limit in ECS prod, when asking for a large (> 90 days) set of daily episodes.
Couple things to maybe help this:

Less big querying

---

lib/castle_web/controllers/api/episode_controller.ex
lib/castle_web/controllers/api/podcast_controller.ex
lib/castle_web/views/api/episode_view.ex
lib/castle_web/views/api/podcast_view.ex
lib/redis/partition_cache.ex
lib/rollup/data/trends_data.ex
lib/rollup/jobs/trends_job.ex
lib/rollup/worker.ex
test/rollup/data/trends_data_test.exs
test/rollup/jobs/trends_job_test.exs
test/views/api/episode_view_test.exs
test/views/api/podcast_view_test.exs

See #52.
Updates podcast/episode `show` views to include:
```
"downloads": {
"yesterday": 64,
"total": 86007,
"today": 45,
"this7days": 425,
"previous7days": 487
}
```
(Totals was already in there).

Rollup for download trends

---

lib/redis/hash_cache.ex
test/redis/hash_cache_test.exs

Was hitting an issue with string-vs-int keys.  Any data coming back from redis has string keys, but any data coming from bigquery has int keys.  So when I merged the 2 together, I'd get something like:
```
%{
1234 => 33333,
"1234" => 444,
}
```
It _should_ have been adding those 2 numbers together, so that podcast-id 1234 has 33777 downloads for that period.  Instead, it tries to hset both of them in redis, and the last one wins ... which is why we're seeing such deflated total downloads for podcasts but not episodes.

Fix podcast totals rollup

---

config/dev.exs
config/prod.exs
lib/big_query/rollup.ex
lib/big_query/rollup/daily_agents.ex
lib/castle/daily_agent.ex
lib/rollup/tasks/agents.ex
priv/repo/migrations/20180530194450_create_daily_agents.exs

~Merge #69 first.  The diff here will be pretty busy until then.~
Implements #70.
- Adds a single `daily_agents` partitioned table (and models/rollups/tasks)
- Rolling up by all 3 of "agent name+type+os" into a single table, and including nulls, there are only about 50K rows per day.  Which is actually a bit less than each of the 3 separate geo tables.  So I think it's fine to use a single table for the 3 facets.
- Uses "0" as an alias for NULLs, so that the postgres constraint/upsert magic works.  (Otherwise, postgres allows duplicate rows, since `null != null`).

User agent rollups

---

lib/castle_web/views/api/episode_view.ex
lib/castle_web/views/api/podcast_view.ex
lib/castle_web/views/api/root_view.ex

Hal service caught that the group and interval params were missing from the views.

adds interval and group to total route params

---

lib/castle.ex
lib/castle_web/views/api/episode_view.ex
lib/castle_web/views/api/podcast_view.ex
lib/castle_web/views/api/root_view.ex
lib/plugs/group_plug.ex
lib/rollup/query/geo_ranks.ex
lib/rollup/query/geo_totals.ex
test/plugs/group_plug_test.exs
test/rollup/query/geo_ranks_test.exs
test/rollup/query/geo_totals_test.exs

Adds a `?filters` param to the ranks and totals endpoints.
Filters are of the form `?filters=key1:value1,key2:value2` (or url encode a `=` instead of `:`).
The only supported filter is for `group=geosubdiv`, and you can filter for one or more country code with:
- `?filters=geocountry:US`
- `?filters=geocountry:CA|US`
- `?filters=geocountry:CA|US|MX`

Filter ranks/totals

---

config/dev.exs
config/prod.exs
lib/postgres/bloat.ex
lib/postgres/tasks/vacuum.ex

For PRX/internal#380
The Postgres upserts we do on the rollup tables cause quite a bit of bloat.  And even when the dead rows are recovered in the `pg_stat_user_tables.n_dead_tup` table, that doesn't mean the storage was recovered.
There are several ways to estimate table bloat (see [this post](https://www.cybertec-postgresql.com/en/estimating-table-bloat/)).  I landed on using a fairly complex pure SQL route, instead of attempting to install a 3rd party extension in RDS.  It finds the "most bloated" tables and runs a full vacuum on them.
Note that for some reason, the thresholds in prod for the daily vs hourly tables are quite different.  Will keep monitoring this to see if the settings I have actually work:
I setup the prod cron to run this every 5 minutes between 8-9 UTC.  So for that …

Full vacuum cron

---

lib/big_query/base/query.ex
lib/big_query/base/query_result.ex
lib/big_query/rollup.ex
lib/big_query/rollup/daily_agents.ex
lib/big_query/rollup/daily_geo_countries.ex
lib/big_query/rollup/daily_geo_metros.ex
lib/big_query/rollup/daily_geo_subdivs.ex
lib/big_query/rollup/hourly_downloads.ex
lib/castle/bucket/daily.ex
lib/castle/bucket/hourly.ex
lib/castle/bucket/monthly.ex
lib/castle/bucket/weekly.ex
lib/rollup/tasks/agents.ex
lib/rollup/tasks/geocountries.ex
lib/rollup/tasks/geometros.ex
lib/rollup/tasks/geosubdivs.ex
lib/rollup/tasks/hourly.ex
test/big_query/base/query_test.exs
test/big_query/rollup/daily_agents_test.exs
test/big_query/rollup/daily_geo_countries_test.exs
test/big_query/rollup/daily_geo_metros_test.exs
test/big_query/rollup/daily_geo_subdivs_test.exs
test/big_query/rollup/hourly_downloads_test.exs
test/big_query/rollup_test.exs
test/castle/bucket/daily_test.exs
test/castle/bucket/hourly_test.exs
test/castle/bucket/monthly_test.exs
test/castle/bucket/weekly_test.exs
test/support/big_query_case.ex

For #107.
BigQuery automatically forces a max-bytes of response payload.  Previously, Castle would page through that and collect all of the rows in-memory before returning to the caller.  This resulted in OOM problems with large result sets (geo-subdivs in particular).
This PR upserts each page of BQ results into Postgres before going on to the next page.  From what I've seen, geo-subdiv rollups have 4 or 5 pages.  So should use maybe %75 less memory doing rollups after this.
(Also fixed some soon-to-be-deprecation problems with `Kernel.floor` and `from_unix`)

Page results for rollups

---

priv/repo/migrations/20191217145133_longer_image_urls.exs

Half of #114
Hitting the varchar 255 limit on some recently imported episodes.  Change both the podcast/episode image_urls to be text instead.

Longer image urls

---

lib/castle/episode.ex
priv/repo/migrations/20200630185355_episodes_have_tags.exs
test/castle/episode_test.exs

See: https://github.com/PRX/augury.prx.org/issues/179 
- Pulls feeder keywords in as part of parsing the episode doc during episode sync.
- Serializes them as an array on the episode model.
Once this is merged, set up the keywords for existing episodes by re-running the episode sync process.

Store feeder episode keywords

---

lib/castle/episode.ex
lib/castle/podcast.ex
lib/castle_web/controllers/api/episode_controller.ex
lib/castle_web/controllers/api/podcast_controller.ex
priv/repo/migrations/20210625173911_add_feeder_deleted_at.exs
test/castle/episode_test.exs
test/castle/hourly_download_test.exs
test/castle/podcast_test.exs
test/controllers/api/episode_controller_test.exs
test/controllers/api/podcast_controller_test.exs

Syncs Feeder `podcasts.deleted_at` and `episodes.deleted_at` to the Augury database.
**NOTE:** this will take a `mix feeder.sync --all --force` to get all the deleted stuff we've already missed (we've passed by their `updated_at` timestamps).
**WHICH MEANS:** that will likely pull in a lot of surprising/deleted stuff into the Metrics UI.  So I did end up hiding deleted podcasts/episodes in the API index endpoints for now.  But we should revisit if that's the right choice.

Sync feeder deleted at

---

.formatter.exs
lib/big_query/base/query.ex
priv/big_query/migrations/20220401201605_remove_deprecated.exs

WOH THERE!  Make sure PRX/analytics-ingest-lambda#86 is deployed and running before doing this.  Otherwise you're going to cause errors.
Actually removes the deprecated columns in "Phase 1: Cleanup Downloads" of [RFC 23](https://github.com/PRX/internal/pull/824).

Remove deprecated columns

---

priv/big_query/migrations/20220622151925_add_feeder_feeds.exs

Adds `feeder_feed` column (naming to match `feeder_podcast` and `feeder_episode`).
I think we want this on both dt_downloads and dt_impressions.
As with all BQ migrations, this must be manually run locally.

Add feeder feed_slug fields

---

priv/big_query/migrations/20230321160811_add_external_ids.exs

Minimal approach for PRX/augury.prx.org#1173.
Just add `integration_id` and `external_id` to the campaigns/flights BQ tables.  That will be enough for us to pull impressions for just those imported-from-external-system flights.

External integrations BigQuery migration

---

lib/castle/episode.ex
priv/big_query/migrations/20240614141751_rename_episode_keywords.exs
priv/repo/migrations/20240614140904_rename_episode_keywords.exs
priv/repo/migrations/20240614140914_add_episode_feed_slugs.exs
test/castle/episode_test.exs

Pull Episode feed_slugs from Feeder API.
Also - stop renaming `episode.categories` to `keywords`.  This is some longstanding confusion/annoyance.  I've renamed both the postgres db here and the BigQuery column.

Episode feeds
